[package]
name = "rbw"
version = "1.8.3"
authors = ["Jesse Luehrs <doy@tozt.net>"]
edition = "2021"

description = "Unofficial Bitwarden CLI"
repository = "https://git.tozt.net/rbw"
readme = "README.md"
keywords = ["bitwarden"]
categories = ["command-line-utilities", "cryptography"]
license = "MIT"
include = ["src/**/*", "bin/**/*", "LICENSE", "README.md", "CHANGELOG.md"]

[dependencies]
aes = "0.8.3"
anyhow = "1.0.72"
argon2 = "0.5.1"
arrayvec = "0.7.4"
async-trait = "0.1.71"
base32 = "0.4.0"
base64 = "0.21.2"
block-padding = "0.3.3"
cbc = { version = "0.1.2", features = ["alloc", "std"] }
clap = { version = "4.3.15", features = ["wrap_help", "derive"] }
clap_complete = "4.3.2"
daemonize = "0.5.0"
# TODO: directories 5.0.1 uses MPL code, which isn't license-compatible
# we should switch to something else at some point
directories = "=5.0.0"
env_logger = "0.10.0"
futures = "0.3.28"
futures-channel = "0.3.28"
futures-util = "0.3.28"
hkdf = "0.12.3"
hmac = { version = "0.12.1", features = ["std"] }
humantime = "2.1.0"
libc = "0.2.147"
log = "0.4.19"
nix = "0.24.3"
pbkdf2 = "0.12.2"
percent-encoding = "2.3.0"
pkcs8 = "0.10.2"
rand = "0.8.5"
region = "3.0.0"
reqwest = { version = "0.11.18", default-features = false, features = ["blocking", "json", "rustls-tls-native-roots"] }
rsa = "0.9.5"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.103"
serde_path_to_error = "0.1.14"
serde_repr = "0.1.14"
sha1 = "0.10.5"
sha2 = "0.10.7"
tempfile = "3.6.0"
terminal_size = "0.2.6"
textwrap = "0.16.0"
thiserror = "1.0.43"
tokio = { version = "1.29.1", features = ["full"] }
tokio-stream = { version = "0.1.14", features = ["net"] }
totp-lite = "2.0.0"
url = "2.4.0"
uuid = { version = "1.4.1", features = ["v4"] }
zeroize = "1.6.0"
copypasta = "0.8.2"
rmpv = "1.0.0"
tokio-tungstenite = { version = "0.19.0", features = ["rustls-tls-native-roots"] }

[package.metadata.deb]
depends = "pinentry"
license-file = ["LICENSE"]
assets = [
    ["target/release/rbw", "usr/bin/", "755"],
    ["target/release/rbw-agent", "usr/bin/", "755"],
    ["target/release/completion/bash", "usr/share/bash-completion/completions/rbw", "644"],
    ["target/release/completion/zsh", "usr/share/zsh/vendor-completions/_rbw", "644"],
    ["target/release/completion/fish", "usr/share/fish/completions/rbw.fish", "644"],
    ["README.md", "usr/share/doc/rbw/README", "644"],
]
